---
kind: pipeline
name: default

steps:
  - name: prepare
    image: python:3
    commands:
      - apt-get update
      - apt-get install git build-essential libssl-dev zlib1g-dev ibbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev
  
  