---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: prepare
    environment:
      - PATH: $$PATH:/home/drone/miniconda3/bin
    commands:
      - molecule test
  # - name: test
  #   commands:
  #     - make build
  
