---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: prepare
    commands:
      - molecule test
  # - name: test
  #   commands:
  #     - make build
  
