---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: prepare
    commands:
      - pipenv install 
      - apt-get install git build-essential make -y
      - make prepare
  - name: test
    commands:
      - make build
  