---

ssh_user: centos
ssh_port: 22

commmon_name: ansible-role-docker
security_group_description: Security group for testing ansible-role-docker
security_group_rules:
  - proto: tcp
    from_port: "{{ ssh_port }}"
    to_port: "{{ ssh_port }}"
    cidr_ip: '0.0.0.0/0'
  - proto: icmp
    from_port: 8
    to_port: -1
    cidr_ip: '0.0.0.0/0'
security_group_rules_egress:
  - proto: -1
    from_port: 0
    to_port: 0
    cidr_ip: '0.0.0.0/0'

keypair_name: "{{ commmon_name }}"
keypair_path: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/ssh_key"

tmppath: "/tmp/ansible_temp_certs"
