---
- name: Ensure docker dirs exists.
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/systemd/system/docker.service.d
    - /etc/docker

- name: Add override to ensure Docker can start in with daemon.json
  template:
    src: docker.conf.j2
    dest: /etc/systemd/system/docker.service.d/docker.conf
  register: override_template

- name: Reload systemd daemon
  systemd:
    name: docker
    daemon_reload: true
    state: "{{ docker_restart_handler_state }}"
  when: override_template is changed

- name: manage daemon.json file
  block:
    - name: create runtime directory
      file:
        path: "{{ docker_data_root }}"
        state: directory
    - name: manage docker daemon json
      template:
        src: daemon.json.j2
        dest: /etc/docker/daemon.json
      notify: restart docker

  when: docker_configure | bool
