---
dependency:
  name: galaxy
driver:
  name: delegated
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: instance
    image_owner: 679593333241
    image_name: "CentOS Linux 7 x86_64 HVM EBS ENA *"
    instance_type: t2.micro
    vpc_subnet_id: subnet-04477b0959af58d38
    instance_tags:
      destroy: true
      Created_by: molecule
      Name: ansible-role-docker
provisioner:
  name: ansible
  playbooks:
    create: create.yml
    converge: converge.yml
    destroy: destroy.yml
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  directory: ../tests
  options:
    v: true
    sudo: true
  lint:
    name: flake8
