---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (yum install python-pip -y && pip install ansible)
      become: true
      changed_when: false
